version: "3"

services:
  # Nginx
  # To enable https uncomment (ports, volumes)
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./src:/var/www
      # - ./your_domain_name/bundle.crt:/etc/ssl/bundle.crt
      # - ./your_domain_name/your_domain_name.key:/etc/ssl/your_domain_name.key
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - app-network

  # ASP.NET Core
  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app
      - mysql
    networks:
      - app-network

  # MariaDB
  mysql:
    image: mariadb
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bitad
      MYSQL_ROOT_PASSWORD: 111111
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  # Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
